version: "3"

volumes:
  mysql_data:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY}
      - SCREENSCRAPER_USER=${SCREENSCRAPER_USER}
      - SCREENSCRAPER_PASSWORD=${SCREENSCRAPER_PASSWORD}
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY}
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY}
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED}
    volumes:
      - /volume1/docker/romm/resources:/romm/resources
      - /volume1/docker/romm/redis-data:/redis-data
      - /volume1/data/games/roms:/romm/library
      - /volume1/data/games/assets:/romm/assets
      - /volume1/data/games/config:/romm/config
    ports:
      - 7676:8080
    network_mode: rommbridge
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWD}
    ports:
      - 3309:3306
    network_mode: rommbridge
    volumes:
      - /volume1/docker/mariadb-romm:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
