version: '3.8'

services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    ports:
      - 3000:3000
    volumes:
      - data:/data
    environment:
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      BROWSER_COOKIE_PATH: /data/cookies.json
      DATA_DIR: /data

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    command:
      - --no-sandbox
      - --remote-debugging-port=9222

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    volumes:
      - meilisearch:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"

volumes:
  data:
  meilisearch:
